spring.application.name=modulo01
server.port=8082

#12 - Mudando o comportamento da aplicação com Spring Profiles
spring.profiles.active=prod

#15 - Criando e acessando propriedades customizadas com @Value
notificador.email.host-servidor=smtp.algafood.com.br
notificador.email.porta-servidor=25